### ISSUE TITLE
Campaign Detail Edit Form missing margin

### ISSUE THREAD

**Issue by lukereative** [silverstripe/silverstripe-campaign-admin#100]
The form rendered by `renderDetailEditView` is missing, this is due to some weird CSS rules with negative margins on 'padded panels' and the fact that this edit form is rendered in react rather than PHP, thus has a different markup than the usual edit form. Ideally we'd unify the two markups so the CSS can be reliably shared between the two.

![silverstripe - campaigns 2018-05-07 14-39-37](https://user-images.githubusercontent.com/1415622/39682529-83a8f7fa-5204-11e8-8f61-3db25997f6ce.png)

**Comment by robbieaverill** [comment]
Fixed by #124

**Comment by clarkepaul** [comment]
Re-opening this issue as the problem still exists with exactly the same issue—perhaps this was a regression.

**Comment by robbieaverill** [comment]
It's definitely fixed in the `1.3` branch. The demo site is running `4.3.0` (`1.3.0` in this module) which isn't fixed, but it'll be in the next patch release (`4.3.1`).
