### ISSUE TITLE
Campaign UX needs to be looked at

### ISSUE THREAD

**Issue by sunnysideup** [silverstripe/silverstripe-campaign-admin#126]
## Affected Version

SS4.3

## Description

We need to improve focus on UX in the CMS. Here are some examples:

![image](https://user-images.githubusercontent.com/167154/50961623-0dc16300-152d-11e9-9ee2-7fab4f30f198.png)

The bottom question mark does something unexpected (it toggles help rather than providing it).  Just remove it, it is necessary until help is closed.  Also note that the other question mark (above on the lft) does not do anything - again - confusing. 

Scroll bar is not required.

The "Add Campaign" button could be bigger and centered?  

Spacing is all out once you start to create a campaign:
![image](https://user-images.githubusercontent.com/167154/50961746-642ea180-152d-11e9-8ff4-4be4ee6a0779.png).

Once you start building a campaign, the UX is actually really good (well, I think so anyway).

**Comment by ScopeyNZ** [comment]
I'm going to triage this as a bug as that padding should _not_ be like that.

**Comment by robbieaverill** [comment]
That particular issue should have been resolved with https://github.com/silverstripe/silverstripe-campaign-admin/issues/100

**Comment by clarkepaul** [comment]
The spacing issue on the "Add campaign" screen still exists (using the current demo 4.3 with Chrome), I'll re-open that issue.

**Comment by clarkepaul** [comment]
For the campaign help screen, it was intended to contain more text and links but at the time help wasn't written and the feature set was still unknown. We design to types of in-page help patterns which could start to be utilised in other areas of the CMS. This isn't a good example as it was not completed as it was designed. For reference you can view [the intended designs ](https://projects.invisionapp.com/dsm/silver-stripe/silver-stripe/asset/components/5be249579efd15001bb0a4d4)

**Comment by clarkepaul** [comment]
I've opened an issue to communicate improved text within the Campaign Intro area here https://github.com/silverstripe/silverstripe-campaign-admin/issues/127
